### ISSUE TITLE
Very Easily Bypassed

### ISSUE THREAD

**Issue by OFWModz** [cutielovesyou/VRC-Anti-Crash#1]
This can literally be bypassed by dragging a crash shader into notepad and replicating poiyomi's shader name.

A better version of this with the same name already exists, and you infringing on it is a little 🤔 

https://vrcanticrash.com

**Comment by OFWModz** [comment]
I am open to you helping develop it or simply use it.

**Comment by cutielovesyou** [comment]
lol gtfo its not even a shader anti crash wtf are you on about

**Comment by OFWModz** [comment]
Then what's the point mate? xD
